version: "3"

services:
  redis-server:
    image: bitnami/redis:4.0
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  katsubushi:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 11212:11212
    command: >
      /opt/katsubushi-server/wait-for-it.sh
        -h redis-server
        -p 6379
        -t 600
        -- 
          /opt/katsubushi-server/bin/katsubushi
            -redis "redis://redis-server:6379/0" 
            -log-level debug
            -port 11212
