name: Tests

on:
  - push

jobs:
  test-docker-container:
    name: Test and Push
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull builder image
        run: |
          REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')  
          docker pull docker.pkg.github.com/$REPOSITORY/katsubushi-server:builder || true

      - name: Pull server image
        run: |
          REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')  
          docker pull docker.pkg.github.com/$REPOSITORY/katsubushi-server:latest || true

      - name: docker-compose run
        shell: bash
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker-compose build
          docker-compose up -d
          ./wait-for-it.sh -h localhost -p 6379 -t 600
          ./wait-for-it.sh -h localhost -p 11212 -t 600
          echo GET 1 | nc -N localhost 11212

      - name: Build builder image
        run: |
          REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]') 
          docker build . --target builder -t katsubushi-server:builder --cache-from=docker.pkg.github.com/$REPOSITORY/katsubushi-server:builder

      - name: Push builder image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')  
          docker tag katsubushi-server:builder docker.pkg.github.com/$REPOSITORY/katsubushi-server:builder
          docker push docker.pkg.github.com/$REPOSITORY/katsubushi-server:builder

      - name: Build server image
        run: |
          REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')  
          docker build . -t katsubushi-server:latest --cache-from=docker.pkg.github.com/$REPOSITORY/katsubushi-server:builder --cache-from=docker.pkg.github.com/$REPOSITORY/katsubushi-server:latest

      - name: Push server image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')  
          docker tag katsubushi-server:latest docker.pkg.github.com/$REPOSITORY/katsubushi-server:latest
          docker tag katsubushi-server:latest docker.pkg.github.com/$REPOSITORY/katsubushi-server:$GITHUB_SHA
          docker push docker.pkg.github.com/$REPOSITORY/katsubushi-server:latest
          docker push docker.pkg.github.com/$REPOSITORY/katsubushi-server:$GITHUB_SHA
